name: Node CI

on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: dev
          BRANCH: master
          FOLDER: public
          BUILD_SCRIPT: npm i -g hexo && npm install && hexo generate && hexo deploy
