name: Node CI

on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@hexo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: dev
          PUBLISH_DIR: ./public
          SCRIPT_MODE: true
          run: |
            wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
            bash ./entrypoint.sh
